#docker-compose -f docker-compose.yml down -v
#docker run -it postgres psql -U postgres -W postgres rest
version: "3.8"

services: 

    tomcat:
        image: tomcat:9.0
        container_name: tomcat
        networks: 
            - red_tomcat
        #restart: always
        ports: 
            - "8888:8080"
        links:
            - postgres
    postgres:
        image: postgres:latest
        container_name: postgres
        networks: 
            - red_tomcat
        #restart: always
        ports: 
            - "15432:5432"
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DBUSER=carlos
            - POSTGRES_DB=rest
            - postgres=/var/lib/postgresql/data/pgdata
        volumes: 
            - postgres:/var/lib/postgresql/data:rw

volumes: 
    postgres:

networks:
    red_tomcat: