version: '2'
services:
  mongo:
    image: mongo
    volumes:
      - ./mongo:/data/db
      - ./user:/root
  mongo-express:
    image: mongo-express
    ports:
      - 98081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root