version: '3'
services:

  mysql:
    container_name: mysql
    image: mysql:8.0.12
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "93306:3306"
    volumes:
      - "./data:/var/lib/mysql"
      - "./user:/root"
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    container_name: 'phpmyadmin'
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 93306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    
    ports:
      - '8050:80'
    volumes: 
      - /sessions
